### ISSUE TITLE
Stress testing send_receive.c fails

### ISSUE THREAD

**Issue by pthreat** [Theldus/wsServer#40]
I stress tested the  send_receive example with artillery.io

```
--------------------------------------
Metrics for period to: 10:55:20(-0300) (width: 9.004s)
--------------------------------------

vusers.created_by_name.0: ................................... 80
vusers.created.total: ....................................... 80
vusers.failed: .............................................. 24
vusers.completed: ........................................... 56
vusers.session_length:
  min: ...................................................... 1.2
  max: ...................................................... 12.4
  median: ................................................... 5.9
  p95: ...................................................... 10.3
  p99: ...................................................... 10.9
websocket.send_rate: ........................................ 29/sec
websocket.messages_sent: .................................... 224
errors.Parse Error: Expected HTTP/: ......................... 24
```

I have tried to increase the amount of clients and ports and recompiling the example, however it still fails.

Do I need to augment file descriptors on my system in order to allow many clients sending and receiving at the same time?

PS: I like the interface of this library it's very intuitive, great work!

**Comment by pthreat** [comment]
Got nothing useful out of enabling debug, I still see the output addr being set to null for some reason, I have increased clients to 200000 and also ports, no idea what's going on

**Comment by Theldus** [comment]
Hi @pthreat,
This is curious, could you tell me how you performed these tests? I'm not familiar with artillery.io.

AFAIR, wsServer manages to pass in [Autobahn's massconnect mode](https://github.com/crossbario/autobahn-testsuite/blob/master/doc/usage.rst#mode-massconnect) (for something like 1k clients), so I can't say exactly what's going on.

Perhaps the "vusers.failed" occurs due to some kind of timeout, because wsServer takes a while to respond or something like that (since wsServer is _very simple_ in connection management, etc).

> Got nothing useful out of enabling debug, I still see the output addr being set to null for some reason, I have increased clients to 200000 and also ports, no idea what's going on

200k clients is indeed a massive amount of clients, and I would be very surprised if wsServer could manage this, since wsServer is not async and [uses one thread per client](https://github.com/Theldus/wsServer/issues/15).

If you need a server for such a large number of clients, maybe wsServer is not the right server for you =/.

**Comment by pthreat** [comment]
@Theldus  Hey man, glad to see you around, I'll paste the test script:

Put this in stress.yml

```
config:
  target: "ws://127.0.0.1:8080"
  phases:
    - duration: 100
      arrivalRate: 8
  ws:
    # Ignore SSL certificate errors
    # - useful in *development* with self-signed certs
    rejectUnauthorized: false
scenarios:
  - engine: "ws"
    flow:
      - send: '{"event":"hello", "token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "application":"frontend"}'
      - send: '{"event":"hello", "token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "application":"frontend"}'
      - send: '{"event":"hello", "token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "application":"frontend"}'
      - send: '{"event":"hello", "token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "application":"frontend"}'
```

Install artillery (through node's npm)

```
npm -g install artillery
```

Then:

artillery run stress.yml
